---
name: latex
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compile in latex
        uses: xu-cheng/latex-action@v4
        with:
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          working_directory: .
          root_file: main.tex
          texlive_version: latest
          pre_compile: tlmgr update --self && tlmgr update --all
      - name: release
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifact: main.pdf
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
